### ISSUE TITLE
Exercises Task List

### ISSUE THREAD

**Issue by lucasfcosta** [lucasfcosta/react-redux-experiments#1]
Well, let's include some exercises and use this issue to track them down:

- [x] Simple Counter
- [ ] Todo App (Add Todo, Toggle Todo, Remove Todo)
- [ ] Todo App (Add/Toggle/Remove and Filter Todos)
- [ ] Pokédex (Use ajax to fetch data for pokémon, remember to use redux thunk)

I'll be adding more exercises here whenever I create one.
